### PR TITLE
fix: fixes scrolling behavior and removes name from edit form

### LINKED ISSUE #26: Improve panning behavior on mobile
Currently, you can pan the map with one finger on mobile devices. This is not good because if the map is full-width, you get stuck on a mobile website.

We should disable one finger panning and only allow two finger panning.

### PR DESCRIPTION
**Pull request by shafy**
Closes #26 and #30

### CODE REVIEW

**Comment by shafy** [comment]
As discussed, we will implement the `cooperativeGestures` as a URL param in like so:
`https://app.mapzy.io/maps/mHy12?no_accidental_zoom=true`.

This will pervent accidental zoom on desktop and mobile. In the future, we can also provide separate params for desktop and mobile, but this is probably too much for now.

**Comment by sagzy** [comment]
> As discussed, we will implement the `cooperativeGestures` as a URL param in like so: `https://app.mapzy.io/maps/mHy12?no_accidental_zoom=true`.
> 
> This will pervent accidental zoom on desktop and mobile. In the future, we can also provide separate params for desktop and mobile, but this is probably too much for now.

Great!

To the name removal: I think it's fine to leave it in the account settings; this way the sign up process is still quick but the user can put their name when they want to. I mean why not? However if you still prefer to remove it, also fine with me. In that case, let's also delete the database column?

**Comment by shafy** [comment]
Oh, I thought you had removed the DB column. Well, I don't see why anybody would want to add their name? I think it's better if we don't have the name, one fewer piece of PII to worry about. Let me delete the DB col also.

**Comment by sagzy** [comment]
Ok :)

**Comment by shafy** [comment]
@sagzy done! Have a look and then we can merge this bad boy!

**Comment by shafy** [comment]
It's weird that the specs fail on GitHub actions. It's somehow not setting up the db correctly and can't find User.name (which I removed)

**Comment by shafy** [comment]
@sagzy can we merge this?

**Review by sagzy — APPROVED** [review]
Looks good too! Thanks @shafy.

I think our embed instructions can be improved (for later):
- Tip 1 (height / width values): it's not clear why we put width as a relative value (100%) and height with pixels and how the user can change that. I think we should explain this better and an example or two would help
- Tip 2: it's rather technical; for a user who doesn't know anything about urls & query params, it won't be easy to understand. A ready-made code that the user can copy would help here.

But I'd say, let's still release this and add a todo to improve on the embedding instructions later?

**Comment by shafy** [comment]
Thanks @sagzy. Yes for sure these are good ideas. I suggest to add the detailed instructions in our docs and then link to them.

**Pull request merged**
