### PR TITLE
Add Embed Code

### PR DESCRIPTION
**Pull request by shafy**
This PR adds the Embed Code and in the wake of that also changed the UX/UI a bit. Specifically, there is only one main call to action "Add Location" in the map view. The thinking behind this is that the user usually only needs the embed code once (or very rarely), so it shouldn't be as prominent as adding location:

Screenshot 2021-11-08 at 6 49 37 PM

When you click on "Show Embed Code", you see this:

Screenshot 2021-11-08 at 6 53 34 PM

I've also fixed some UI bugs in the add location view (the time dropdowns were too big and all cramped over each other). They're a bit smaller now:

Screenshot 2021-11-08 at 6 49 26 PM

_(I've already fixed the wrong pin color you see in this screenshot)_

As you can see, I've also changed the colors and got rid of the violet. This was Dorena's feedback actually. The reason is that the violet is too close to the blue of mapbox and doesn't really stand out. I agreed with her and changed the colors. I think it looks great!

Furthemore, in the "Add Location" view, the Mapbox map container's width is now so that there is no overlap. Therfore, when adding a pin, the pin is always displayed in the center of the visible map (before that the map was under the add location overlay, and it's center wasn't the same as the visible center).

Finally, I've changed Capybara to work with Chrome Headless (and added Chrome installation to `.gitpod.Dockerfile`) and added two feature tests for the new embed code feature.

### CODE REVIEW

**Comment by sagzy** [comment]
Code: I found nothing to comment on, it looks clean!

Product:
As I already said, LOVE the new color & feel of the map & dashboard! Thanks for fixing some of the UI / layout bugs as well.

- Show/Hide Embed Code: I like that the instructions are simple and it's easy for someone familiar with HTML to apply them. On the other hand, for users that are not, I wonder if we should babysit them more. For example, we could add help links on how to do it for typical CMS / website builders like Wordpress, Shopify, Webflow. What do you think?
- Show/Hide Embed Code: the title is a bit technical. What about "Install Map"?
- Lower menu bar: I agree with you, it didn't make much sense to have "Add Location" and "Install Map" as two big call to actions, as one installs the map only once. I think we should actually get rid of the lower menu altogether (i.e. Move "Install Map" to the top menu & just have a floating "Add location" button at the bottom), it'll look better. But we can do that later.
- Color: while the general feel with the mapzy red is great, I think in some cases the it's too strong and gives a wrong signal (= error). For instance in the flash message. So I suggest we use the orange or the violet as secondary color, for the flash message and / or for when we need to highlight something. what do you think?

**Comment by shafy** [comment]
Thanks for your feedback!

- Embed code instructions: Yes, as soon as we have some guides in our Docs I would link them there. I would go public before adding the Docs, though
- Yes, floating button sounds like a good idea - let me see if I can make it work quickly
- Yes, good point - will update the flash messages

**Comment by sagzy** [comment]
Awesome, thanks! 

To the merge conflict: I've updated the main Dockerfile to be used for production, so I suggest not adding Chrome there (as we won't be running any features tests there). We can add it to Dockerfile.dev though

**Comment by shafy** [comment]
> Does this screw up anything for the gitpod setup btw? Or gitpod doesn't rely on the Dockerfile?

All good - Gitpod only relies on `.gitpod.Dockerfile` :-)

**Comment by shafy** [comment]
I've implemented your feedback. Sorry for the `Dockerfile` - I meant to add the Chrome installation to `.gitpod.Dockerfile` (fixed now).

I decided to move the embed code to the settings, I think it makes much more sense and makes for a cleaner UI on the map screen, especially with the bottom menu removed.

Screenshot 2021-11-15 at 11 38 50 AM

Screenshot 2021-11-15 at 11 46 43 AM

I also changed the the default link style from the underline to our red light, looks cooler I think.

Updated the flash styling also:

Screenshot 2021-11-15 at 11 45 03 AM

I removed the "Docs" link from the header for now since we don't have any Docs yet :D

**Comment by sagzy** [comment]
Great stuff! Much cleaner without the bottom menu & I like the new UI of the links.

Only one comment: I think it's not very intuitive to find the installation instructions under Settings. As a user if I'm done with setting up my map and want to put it on my website, I wouldn't look for these under Settings. I would look for something explicit from the dashboard or click on "Help".

Here's an idea that goes mostly in the same direction, but makes the path to finding the instructions easier:
- when the user is on the map, replace the "Map" link by "Install Map". This link goes to a settings-alike full screen and show the installation instructions. Later on we can make this page more complete with examples & links to docs.
- when the "Install Map" is open, replace the name of the menu item by "Live Map" (= redirects the users to the map)

What do you think?

Also then it'll be easier to add an onboarding feature: when the user signs up, highlight the "Add Location" Button. Once they've added one, highlight the "Install Map" instructions. etc. Guide them a little bit about what they need to do to get this store rolled out.

**Comment by shafy** [comment]
Ok, that makes sense. I'll make the changes. Also, realized that we need to remove  the `X-Frame-Options` header, otherwise it doesn't allow embedding from another domain.

```

**Comment by shafy** [comment]
Although, I would still argue that you only embed the map once and therefore only need to access the embed code once. Maybe another time when you have a new website or something. Therefore, having a link that's displayed constantly but that you never need is not great UX.

I think when you click on Settings (which you need to do anyways to pay) you'll see that the embed code is there. It's not like there are 5 different menus or places where it could hide.

So, maybe let's launch like this and based on customer feedback we'll see how it goes? We can always change it later if you really hate it.

**Comment by sagzy** [comment]
I can follow your reasoning, but I think at this stage we should optimise the experience for new users and make it dead simple for them to know what they need to do to get their first map out. Hiding the instructions under Settings does not go into this direction. We can always have a “Mark as done” button in there later on to hide it later on.

**Comment by shafy** [comment]
Ok, if you insist :-)

**Comment by shafy** [comment]
Ok! Implemented it as discussed and also added code that removes `X-Frame-Options` response header from `/maps/:id`.

**Comment by sagzy** [comment]
Thanks my man! Looks good to go :D

**Review by sagzy — APPROVED** [review]

**Pull request merged**
