### PR TITLE
HashID, UI Improvements & Little Bug Fixes

### PR DESCRIPTION
**Pull request by sagzy**
This PR:
- Add HashID for the embed map (e.g. `maps/ZxOHrm` instead of `maps/36`) & also on map / location routes in general
- Fixes Stripe Checkout bug
- Harmonises UI with the landing page (square logo, underline red, buttons, etc.)
- Makes the dashboard responsive for smaller screens / resolutions

Ah also, I reverted back the opening times to be on a single line; the form looks longer and more painful to fill otherwise. Hope you don't mind :D

Some screenshots:
Screenshot 2021-11-25 at 21 53 39
Screenshot 2021-11-25 at 21 56 41
Screenshot 2021-11-25 at 22 06 09

### CODE REVIEW

**Comment by shafy** [comment]
Looks good, I like the UI changes. Why did you move redis out of Foreman though?

**Comment by sagzy** [comment]
It was buggy for me (redis port would be already taken or sidekiq would
start before redis was up). I've moved the `redis-server` command to
gitpod.yml though as an init command. Works for me this way, also on
gitpod. You?

-- 
Sagar Gupta

**Comment by shafy** [comment]
Yes works for me to, just wanted to see why you did it. But I also didn't have any problems with it being in the Procfile.

**Comment by shafy** [comment]
Looks good to me, you can merge!

**Pull request merged**
