### PR TITLE
feature: moves map if locaton panel hides marker

### LINKED ISSUE #27: Center map on pin click if pin is in left 1/3 of current view
We should center the map if the pin is in the left 1/3 of the view when clicked, otherwise it gets hidden by the location panel that pops up. If this is not easily achievable with the Mapbox API, I suggest just always centering the map on Marker click.

### PR DESCRIPTION
**Pull request by shafy**
Knocked this one out of the park:

https://user-images.githubusercontent.com/1881676/144717401-a6bfa635-0756-48f7-9c9a-3c2b90742355.mp4

Closes #27

### CODE REVIEW

**Comment by shafy** [comment]
I've also moved the location panel on mobile to the bottom. I think it looks better!

**Comment by shafy** [comment]
I think this should also work correctly when embedded. We'll see :D

**Comment by sagzy** [comment]
Beauty! Works as smoothly as f*cking possible. Great work @shafy

**Comment by shafy** [comment]
Thanks @sagzy!

**Pull request merged**
