### PR TITLE
fix: clear flash after it has been rendered

### LINKED ISSUE #51: Don't show flash messages when map is embedded
For example, if you're logged in and visit the a website where you have embedded your map, it will show you the a flash message (e.g., that you're trial is about to expire). Not a big deal since it would only be shown to account owners, but it might be irritating for users because they might think that everybody sees it.

### PR DESCRIPTION
**Pull request by sagzy**
Closes #51 

I couldn't reproduce the error locally, so I have deployed this to production once to check.

Before:
Visiting https://app.mapzy.io/dashboard/maps/ZxOHrm then https://app.mapzy.io/maps/ZxOHrm would keep the flash on

After:
Not anymore

### CODE REVIEW

**Review by shafy — APPROVED** [review]
Ok looks good!

Edit: I just checked on mapzy.io and I still see the flash message. I think rather than clearing the flash message we need to to not display it at all if the map is embedded?

**Comment by shafy** [comment]
Made a suggestion in [af4ab50](https://github.com/mapzy/mapzy/pull/67/commits/af4ab501f3e01595ecc1c87a841e6b66653559ad). What do you think?

**Comment by sagzy** [comment]
> Ok looks good!
> 
> Edit: I just checked on mapzy.io and I still see the flash message. AFAIK the clear only hides the flash message after a redirect or refresh? I think rather than clearing the flash message we need to to not display it at all if the map is embedded?

Ah no, I just deployed it for 2 minutes to try it then deployed the main branch again. It's not live anymore. But it works with the first commit.

So I think [af4ab50](https://github.com/mapzy/mapzy/pull/67/commits/af4ab501f3e01595ecc1c87a841e6b66653559ad) is not necessary.

**Comment by shafy** [comment]
@sagzy ah yes, makes sense, of course we don't render it haha. I reset to the previous commit.

**Pull request merged**
